#!/usr/bin/python3


def reduce_polymer(polymer):
    while True:
        length = len(polymer)
        for ptr in range(0, length - 1):
            left = polymer[ptr]
            right = polymer[ptr + 1]
            match_1 = left.islower() and right.isupper()
            match_2 = left.isupper() and right.islower()
            same_char = left.lower() == right.lower()
            if (match_1 or match_2) and same_char:
                del polymer[ptr]
                del polymer[ptr]
                break
        if length == len(polymer):
            break


def part_1(polymer):
    reduce_polymer(polymer)
    print("Reduced polymer length = {}".format(len(polymer)))


def part_2(polymer):
    min_char = None
    min_len = len(polymer)
    for code in range(ord("a"), ord("z")):
        ch = chr(code)
        material = list(filter(lambda c: c.lower() != ch, polymer))
        if len(material) != len(polymer):
            reduce_polymer(material)
            new_length = len(material)
            if new_length < min_len:
                min_char = ch
                min_len = len(material)
    print("Character with best yield = {}".format(min_char))
    print("Length of yielded polymer = {}".format(min_len))


def main():
    with open("day5.txt") as data:
        polymer = list(list(data)[0])
        # polymer = list("dabAcCaCBAcCcaDA")
        # part_1(polymer.copy())
        part_2(polymer.copy())


if __name__ == '__main__':
    main()

