#!/usr/bin/env python3

# for real data, 60 seconds + name
# TIME_OFFSET = -4

# for test data, a = 1 second, b = 2 seconds, etc
TIME_OFFSET = -64


class WorkerState:
    def __init__(self):
        self.step = None
        self.seconds = 0


    def start_step(self, step):
        self.step = step
        self.seconds = 0


    def tick(self):
        if self.step:
            self.seconds += 1
            if self.seconds == self.step.time:
                return self.step.name


    def available(self):
        return self.step == None or self.step.time == self.seconds


class Step:
    def __init__(self, name):
        self.name = name
        self.time = ord(name) + TIME_OFFSET
        self.deps = []


    def add_dep(self, name):
        self.deps.append(name)


    def __repr__(self):
        return "<Step {}, deps: {}>".format(self.name, self.deps)


def parse_steps(lines):
    steps = {}
    for ln in lines:
        tok = ln.split(" ")
        dep = tok[1]
        name = tok[7]

        if name not in steps:
            steps[name] = Step(name)
        if dep not in steps:
            steps[dep] = Step(dep)

        step = steps[name]
        if dep not in step.deps:
            step.add_dep(dep)
    return sorted(steps.values(), key = lambda s: s.name)


def choose_next_step(seq, steps):
    for st in steps:
        if st.name not in seq and all(map(lambda d: d in seq, st.deps)):
            return st.name


def resolve_dependencies(steps):
    seq = []
    while len(seq) != len(steps):
        next_step = choose_next_step(seq, steps)
        if next_step:
            seq.append(next_step)
        else:
            break
    return seq


def part_1(steps):
    seq = resolve_dependencies(steps)
    print("".join(seq))


def select_idle_workers(workers):
    return list(filter(lambda w: w.available(), workers))


def find(fn, lst):
    for item in lst:
        if fn(item):
            return item


def select_next_available_step(seq, done, steps):
    if bool(seq):
        candidate = find(lambda s: s.name == seq[0], steps)
        if all(map(lambda d: d in done, candidate.deps)):
            seq.pop(0)
            return candidate


def count_time_to_complete(seq, steps, worker_count):
    print("Second   Worker 1   Worker 2   Done")
    seconds = 0
    done = []
    workers = [WorkerState() for _ in range(worker_count)]

    while True:

        for wk in workers:
            if wk.available():
                next_step = select_next_available_step(seq, done, steps)
                if next_step:
                    wk.start_step(next_step)

            completed = wk.tick()

            if completed:
                done.append(completed)
                next_step = select_next_available_step(seq, done, steps)
                if next_step:
                    wk.start_step(next_step)

        preview_progress(seconds, workers, done)
        if len(done) == len(steps):
            break
        else:
            seconds += 1
    return seconds


def part_2(steps):
    seq = resolve_dependencies(steps)
    seconds = count_time_to_complete(seq, steps, 2)
    print("The sequence was built in {} seconds".format(seconds))


def main():
    with open("./test7.txt") as lines:
        steps = parse_steps(list(lines))
        part_1(steps)
        part_2(steps)


def preview_progress(seconds, workers, done):
    [w1, w2] = workers
    [s1, s2] = w1.step, w2.step
    n1 = "."
    n2 = "."
    if s1:
        n1 = s1.name
    if s2:
        n2 = s2.name
    dn = "".join(done)
    print(" {}         {}         {}      {}".format(seconds, n1, n2, dn))


if __name__ == "__main__":
    main()

